"""Export the project deck PDF from rendered PPT slide previews.

This keeps `Submission/project_deck.pdf` visually aligned with the editable
PPTX generated by `tools/generate_project_deck.cjs`.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


ROOT = Path(__file__).resolve().parents[1]
PREVIEW_DIR = ROOT / "Submission" / "project_deck_assets"
OUTPUT_PDF = ROOT / "Submission" / "project_deck.pdf"
OUTPUT_MONTAGE = PREVIEW_DIR / "deck-montage.webp"


def main() -> None:
    slide_paths = sorted(PREVIEW_DIR.glob("slide-*.png"))
    if not slide_paths:
        raise FileNotFoundError("No slide preview PNGs found under Submission/project_deck_assets.")

    pdf = canvas.Canvas(str(OUTPUT_PDF), pagesize=(1280, 720))
    for slide_path in slide_paths:
        pdf.drawImage(ImageReader(str(slide_path)), 0, 0, width=1280, height=720, preserveAspectRatio=False)
        pdf.showPage()
    pdf.save()
    create_montage(slide_paths)
    print(f"Exported {OUTPUT_PDF}")


def create_montage(slide_paths: list[Path]) -> None:
    thumbnail_width = 640
    thumbnail_height = 360
    columns = 2
    rows = (len(slide_paths) + columns - 1) // columns
    montage = Image.new("RGB", (thumbnail_width * columns, thumbnail_height * rows), (255, 248, 253))

    for index, slide_path in enumerate(slide_paths):
        slide = Image.open(slide_path).convert("RGB").resize((thumbnail_width, thumbnail_height), Image.Resampling.LANCZOS)
        x = (index % columns) * thumbnail_width
        y = (index // columns) * thumbnail_height
        montage.paste(slide, (x, y))

    montage.save(OUTPUT_MONTAGE, quality=90)


if __name__ == "__main__":
    main()
